backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

site_url: https://ssteelfabrication.com
display_url: https://ssteelfabrication.com

collections:

  - name: "pages"
    label: "Website Content"
    files:

      - label: "Homepage"
        name: "homepage"
        file: "content/homepage.md"
        fields:
          - {label: "Main Heading", name: "title", widget: "string"}
          - {label: "Sub Heading", name: "subtitle", widget: "text"}
          - {label: "Call Button Text", name: "call_button", widget: "string"}
          - {label: "Whatsapp Button Text", name: "whatsapp_button", widget: "string"}

  - name: "services"
    label: "Services"
    folder: "content/services"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Service Name", name: "title", widget: "string"}
      - {label: "Service Image", name: "image", widget: "image"}
      - {label: "Description", name: "body", widget: "markdown"}

  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Project Name", name: "title", widget: "string"}
      - {label: "Project Image", name: "image", widget: "image"}
      - {label: "Description", name: "body", widget: "markdown"}
