backend:
  name: github
  repo: Anish241A/Stainlesssteelfab
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Homepage"
        name: "home"
        file: "index.html"
        fields:
          - {label: "Title", name: "title", widget: "string"}
